// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-courses.ts
var search_courses_default = defineTool({
  name: "search_courses",
  title: "Search courses",
  description: "Search the published ABD'I course catalog by title, description, or category.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search across title and description."),
    category: z.string().trim().optional().describe("Filter by category name."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("courses").select("id, title, description, category, price, duration, is_featured, total_enrollments, average_rating").eq("is_published", true).limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course details",
  description: "Fetch one published course with its lessons by course id.",
  inputSchema: { course_id: z2.string().uuid().describe("The course id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: course, error } = await supabase.from("courses").select("*").eq("id", course_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!course) return { content: [{ type: "text", text: "Course not found" }], isError: true };
    const { data: lessons } = await supabase.from("lessons").select("id, title, description, duration, sort_order").eq("course_id", course_id).order("sort_order");
    const payload = { course, lessons: lessons ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/my-progress.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var my_progress_default = defineTool3({
  name: "my_progress",
  title: "My learning progress",
  description: "Get the signed-in learner's XP, level, streaks, and course enrollments with progress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [statsRes, enrollRes] = await Promise.all([
      supabase.from("user_stats").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("enrollments").select("course_id, xp_earned, viewed_lessons, updated_at, courses(title, category)").eq("user_id", userId)
    ]);
    if (statsRes.error) return { content: [{ type: "text", text: statsRes.error.message }], isError: true };
    if (enrollRes.error) return { content: [{ type: "text", text: enrollRes.error.message }], isError: true };
    const payload = { stats: statsRes.data ?? null, enrollments: enrollRes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_task_default = defineTool4({
  name: "create_daily_task",
  title: "Create daily study task",
  description: "Add a study task to the signed-in learner's daily plan.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Task title."),
    description: z3.string().trim().optional().describe("Optional task detail."),
    task_type: z3.string().trim().optional().describe("Task type, e.g. study, revise, quiz."),
    task_date: z3.string().trim().optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    xp_reward: z3.number().int().min(0).max(500).optional().describe("XP granted on completion.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, task_type, task_date, xp_reward }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_tasks").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      task_type: task_type ?? "study",
      ...task_date ? { task_date } : {},
      ...xp_reward !== void 0 ? { xp_reward } : {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Task created: ${data?.title}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/create-flashcard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_flashcard_default = defineTool5({
  name: "create_flashcard",
  title: "Create flashcard",
  description: "Save a flashcard (front/back) to the signed-in learner's study deck.",
  inputSchema: {
    front: z4.string().trim().min(1).describe("Question or prompt side."),
    back: z4.string().trim().min(1).describe("Answer side."),
    topic: z4.string().trim().optional().describe("Optional topic label."),
    course_id: z4.string().uuid().optional().describe("Optional course to attach the card to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ front, back, topic, course_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("flashcards").insert({
      user_id: ctx.getUserId(),
      front,
      back,
      topic: topic ?? null,
      course_id: course_id ?? null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Flashcard saved: ${data?.front}` }],
      structuredContent: { flashcard: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tbjlkqxjkcktdzwidzje";
var mcp_default = defineMcp({
  name: "abd-i",
  title: "Abd'i",
  version: "0.1.0",
  instructions: "Tools for the ABD'I learning platform. Browse the course catalog, read the signed-in learner's XP/streaks/enrollments, and add study tasks or flashcards to their plan.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_courses_default, get_course_default, my_progress_default, create_task_default, create_flashcard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
